# Generated by Django 5.1.5 on 2025-01-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicionariousuario',
            name='notificacoes',
        ),
        migrations.RemoveField(
            model_name='dicionariousuario',
            name='preferencias',
        ),
        migrations.RemoveField(
            model_name='dicionariousuario',
            name='tema_preferido',
        ),
        migrations.AddField(
            model_name='dicionariousuario',
            name='user_dict',
            field=models.JSONField(default=dict),
        ),
    ]
